---
- name: Set cluster for kube-proxy kubeconfig
  shell: |
    kubectl config set-cluster kubernetes-the-hard-way \
      --certificate-authority=certs/ca.pem \
      --embed-certs=true \
      --server=https://{{ kubernetes_public_address }}:6443 \
      --kubeconfig=kube-proxy.kubeconfig

- name: Set credentials for kube-proxy kubeconfig
  shell: |
    kubectl config set-credentials kube-proxy \
      --client-certificate=certs/kube-proxy.pem \
      --client-key=certs/kube-proxy-key.pem \
      --embed-certs=true \
      --kubeconfig=kube-proxy.kubeconfig

- name: Set context for kube-proxy kubeconfig
  shell: |
    kubectl config set-context default \
      --cluster=kubernetes-the-hard-way \
      --user=kube-proxy \
      --kubeconfig=kube-proxy.kubeconfig

- name: Use context for kube-proxy kubeconfig
  shell: |
    kubectl config use-context default --kubeconfig=bootstrap.kubeconfig
