---
- name: Ensure haproxy, xterm is installed
  yum: name={{ item }} state=installed
  with_items:
      - xterm
      - haproxy
  sudo: yes

- name: Copy haproxy config
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  sudo: yes

- name: Ensure haproxy service is enabled and started
  service: name=haproxy enabled=yes state=restarted
  sudo: yes
