---
- name: Ensure that etcd is installed
  yum: name=etcd state=installed
  sudo: yes

- name: Copy certs to /etc/etcd
  copy: src="{{ ansible_env.HOME }}/certs/{{ item }}" dest=/etc/etcd remote_src=yes
  with_items:
      - ca.pem
      - kubernetes.pem
      - kubernetes-key.pem
  sudo: yes

- name: Ensure etcd data dir exists
  file: path=/var/lib/etcd state=directory
  sudo: yes

- name: Push etcd service file
  template: src=etcd.service.j2 dest=/etc/systemd/system/etcd.service
  sudo: yes

- name: Enable and restart etcd service
  systemd: name=etcd enabled=yes state=restarted daemon_reload=yes
  sudo: yes

